// <auto-generated />
using System;
using Infrastructure.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ContextBase))]
    [Migration("20221115144558_tipoPessoaEmpresaUnidade")]
    partial class tipoPessoaEmpresaUnidade
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Entities.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("CaminhoImagem")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CaminhoImagem_Usuario");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Nome")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Nome_Usuario");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("StatusUsuario")
                        .HasColumnType("bit")
                        .HasColumnName("Status_Usuario");

                    b.Property<int?>("Tipo")
                        .HasColumnType("int")
                        .HasColumnName("Tipo_Usuario");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UltimoAcesso")
                        .HasColumnType("datetime2")
                        .HasColumnName("UltimoAcesso_Usuario");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Entities.Entities.Atendimentos.Agendamento", b =>
                {
                    b.Property<int>("IdAgendamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_Agendamento");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAgendamento"), 1L, 1);

                    b.Property<int>("CompromissoAgendamento")
                        .HasColumnType("int")
                        .HasColumnName("compromisso_Agendamento");

                    b.Property<DateTime>("DataAgendamento")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_Agendamento");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("dataAlteracao_Agendamento");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2")
                        .HasColumnName("dataCadastro_Agendamento");

                    b.Property<string>("FuncionarioAgendamento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("funcionario_Agendamento");

                    b.Property<DateTime>("HoraAgendada")
                        .HasColumnType("datetime2")
                        .HasColumnName("hota_Agendamento");

                    b.Property<string>("RazaoSocialAgendamento")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("razaoSocial_Agendamento");

                    b.Property<int>("StatusAgendamento")
                        .HasColumnType("int")
                        .HasColumnName("status_Agendamento");

                    b.Property<int?>("TipoCompromissoAgendamento")
                        .HasColumnType("int")
                        .HasColumnName("tipoCompromisso_Agendamento");

                    b.HasKey("IdAgendamento");

                    b.ToTable("Agendamento");
                });

            modelBuilder.Entity("Entities.Entities.Atendimentos.Atendimento", b =>
                {
                    b.Property<int>("IdAtendimento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_Atendimento");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAtendimento"), 1L, 1);

                    b.Property<string>("AtendimentoAtendimento")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("atendimento_Atendimento");

                    b.Property<string>("CPFAtendimento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("cpf_Atendimento");

                    b.Property<string>("CargoAtendimento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("cargo_Atendimento");

                    b.Property<int>("CompromissoAtendimento")
                        .HasColumnType("int")
                        .HasColumnName("compromisso_Atendimento");

                    b.Property<DateTime>("DataAgendamentoAtendimento")
                        .HasColumnType("datetime2")
                        .HasColumnName("dataAgendamento_Atendimento");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("dataAlteracao_Atendimento");

                    b.Property<DateTime>("DataAtendimento")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_Atendimento");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2")
                        .HasColumnName("dataCadastro_Atendimento");

                    b.Property<string>("FuncionarioAtendimento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("funcionario_Atendimento");

                    b.Property<DateTime?>("HoraAgendadaAtendimento")
                        .HasColumnType("datetime2")
                        .HasColumnName("horaAgendada_Atendimento");

                    b.Property<DateTime?>("HoraFinalAtendimento")
                        .HasColumnType("datetime2")
                        .HasColumnName("horaFinal_Atendimento");

                    b.Property<DateTime>("HoraInicialAtendimento")
                        .HasColumnType("datetime2")
                        .HasColumnName("horaInicial_Atendimento");

                    b.Property<string>("IdUsuarioAtendimento")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MatriculaAtendimento")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("matricula_Atendimento");

                    b.Property<string>("RGAtendimento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("rg_Atendimento");

                    b.Property<string>("RazaoSocialAtendimento")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("razaoSocial_Atendimento");

                    b.Property<string>("SetorAtendimento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("setor_Atendimento");

                    b.Property<int>("StatusAtendimento")
                        .HasColumnType("int")
                        .HasColumnName("status_Atendimento");

                    b.Property<int>("TipoCompromissoAtendimento")
                        .HasColumnType("int")
                        .HasColumnName("tipoCompromisso_Atendimento");

                    b.Property<string>("UnidadeAtendimento")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("unidade_Atendimento");

                    b.HasKey("IdAtendimento");

                    b.HasIndex("IdUsuarioAtendimento");

                    b.ToTable("Atendimento");
                });

            modelBuilder.Entity("Entities.Entities.Cargos.Cargo", b =>
                {
                    b.Property<int>("IdCargo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_Cargo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCargo"), 1L, 1);

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("dataAlteracao_Cargo");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2")
                        .HasColumnName("dataCadastro_Cargo");

                    b.Property<string>("DescricaoCargo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("descricao_Cargo");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<string>("NomeCargo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nome_Cargo");

                    b.Property<bool>("SituacaoCargo")
                        .HasColumnType("bit")
                        .HasColumnName("situacao_Cargo");

                    b.HasKey("IdCargo");

                    b.HasIndex("IdEmpresa");

                    b.ToTable("Cargo");
                });

            modelBuilder.Entity("Entities.Entities.Empresas.AtendimentoEmpresa", b =>
                {
                    b.Property<int>("IdAtendimentoEmpresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_AtendimentoEmpresa");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAtendimentoEmpresa"), 1L, 1);

                    b.Property<int>("IdAtendimento")
                        .HasColumnType("int");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.HasKey("IdAtendimentoEmpresa");

                    b.HasIndex("IdAtendimento");

                    b.HasIndex("IdEmpresa");

                    b.ToTable("AtendimentoEmpresa");
                });

            modelBuilder.Entity("Entities.Entities.Empresas.Empresa", b =>
                {
                    b.Property<int>("IdEmpresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_Empresa");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmpresa"), 1L, 1);

                    b.Property<string>("CnpjEmpresa")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("cnpj_Empresa");

                    b.Property<string>("CpfEmpresa")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("cpf_Empresa");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("dataAlteracao_Empresa");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2")
                        .HasColumnName("dataCadastro_Empresa");

                    b.Property<DateTime?>("DataContratoEmpresa")
                        .HasColumnType("datetime2")
                        .HasColumnName("dataContrato_Empresa");

                    b.Property<string>("InscricaoEstadualEmpresa")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("inscricaoEstadual_Empresa");

                    b.Property<string>("InscricaoMunicipalEmpresa")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("inscricaoMunicipal_Empresa");

                    b.Property<string>("NomeAbreviadoEmpresa")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nomeAbreviado_Empresa");

                    b.Property<string>("NumeroContratoEmpresa")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("numeroContrato_Empresa");

                    b.Property<string>("RazaoSocialEmpresa")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("razaoSocial_Empresa");

                    b.Property<bool>("SituacaoEmpresa")
                        .HasColumnType("bit")
                        .HasColumnName("situacao_Empresa");

                    b.Property<int?>("TipoCliente")
                        .HasColumnType("int")
                        .HasColumnName("tipoCliente_Empresa");

                    b.Property<int?>("TipoPessoa")
                        .HasColumnType("int")
                        .HasColumnName("tipoPessoa_Empresa");

                    b.HasKey("IdEmpresa");

                    b.ToTable("Empresa");
                });

            modelBuilder.Entity("Entities.Entities.Empresas.PessoaEmpresa", b =>
                {
                    b.Property<int>("IdPessoaEmpresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_PessoaEmpresa");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPessoaEmpresa"), 1L, 1);

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<int>("IdPessoas")
                        .HasColumnType("int");

                    b.HasKey("IdPessoaEmpresa");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("IdPessoas");

                    b.ToTable("PessoaEmpresa");
                });

            modelBuilder.Entity("Entities.Entities.Empresas.PrestadorEmpresa", b =>
                {
                    b.Property<int>("IdPrestadorEmpresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_PrestadorEmpresa");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPrestadorEmpresa"), 1L, 1);

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<int>("IdPrestador")
                        .HasColumnType("int");

                    b.HasKey("IdPrestadorEmpresa");

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("IdPrestador");

                    b.ToTable("PrestadorEmpresa");
                });

            modelBuilder.Entity("Entities.Entities.Empresas.Unidade", b =>
                {
                    b.Property<int>("IdUnidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_Unidade");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUnidade"), 1L, 1);

                    b.Property<string>("CnaeLivreUnidade")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("cnaeLivre_Unidade");

                    b.Property<string>("CnaeSecundarioUnidade")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("cnaeSecundario_Unidade");

                    b.Property<string>("CnaeUnidade")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("cnae_Unidade");

                    b.Property<string>("CnoUnidade")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("cno_Unidade");

                    b.Property<string>("CnpjUnidade")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("cnpj_Unidade");

                    b.Property<string>("CpfUnidade")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("cpf_Unidade");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("dataAlteracao_Unidade");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2")
                        .HasColumnName("dataCadastro_Unidade");

                    b.Property<DateTime?>("DataContratoUnidade")
                        .HasColumnType("datetime2")
                        .HasColumnName("dataContrato_Unidade");

                    b.Property<string>("DescricaoLocalUnidade")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("descricaoLocal_Unidade");

                    b.Property<string>("GrauRiscoUnidade")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("grauRisco_Unidade");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<string>("InscricaoEstadualUnidade")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("inscricaoEstadual_Unidade");

                    b.Property<string>("InscricaoMunicipalUnidade")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("inscricaoMunicipal_Unidade");

                    b.Property<string>("NomeAbreviadoUnidade")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nomeAbreviado_Unidade");

                    b.Property<string>("NumeroContratoUnidade")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("numeroContrato_Unidade");

                    b.Property<string>("RazaoSocialUnidade")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("razaoSocial_Unidade");

                    b.Property<bool>("SituacaoUnidade")
                        .HasColumnType("bit")
                        .HasColumnName("situacao_Unidade");

                    b.Property<int?>("TipoPessoa")
                        .HasColumnType("int")
                        .HasColumnName("tipoPessoa_Unidade");

                    b.HasKey("IdUnidade");

                    b.HasIndex("IdEmpresa");

                    b.ToTable("Unidade");
                });

            modelBuilder.Entity("Entities.Entities.Empresas.UsuarioEmpresa", b =>
                {
                    b.Property<int>("IdUsuarioEmpresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_UsuarioEmpresa");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuarioEmpresa"), 1L, 1);

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<string>("IdUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdUsuarioEmpresa");

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("IdUser");

                    b.ToTable("UsuarioEmpresa");
                });

            modelBuilder.Entity("Entities.Entities.Endereco.Endereco", b =>
                {
                    b.Property<int>("IdEndereco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_Endereco");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEndereco"), 1L, 1);

                    b.Property<string>("CepEndereco")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("cep_Endereco");

                    b.Property<string>("CidadeEndereco")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("cidade_Endereco");

                    b.Property<string>("CodigoMunicipioEndereco")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("codigoMunicipio_Endereco");

                    b.Property<string>("ComplementoEndereco")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("complemento_Endereco");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("dataAlteracao_Endereco");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2")
                        .HasColumnName("dataCadastro_Endereco");

                    b.Property<string>("EmailEndereco")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("email_Endereco");

                    b.Property<string>("EnderecoEndereco")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("endereco_Endereco");

                    b.Property<string>("EstadoEndereco")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("estado_Endereco");

                    b.Property<int>("NumeroEndereco")
                        .HasColumnType("int")
                        .HasColumnName("numero_Endereco");

                    b.Property<bool>("StatusEndereco")
                        .HasColumnType("bit")
                        .HasColumnName("status_Endereco");

                    b.Property<string>("TelefoneEndereco")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("telefone_Endereco");

                    b.Property<int>("TipoEndereco")
                        .HasColumnType("int")
                        .HasColumnName("tipo_Endereco");

                    b.HasKey("IdEndereco");

                    b.ToTable("Endereco");
                });

            modelBuilder.Entity("Entities.Entities.Endereco.EnderecoEmpresa", b =>
                {
                    b.Property<int>("IdEnderecoEmpresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_EnderecoEmpresa");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEnderecoEmpresa"), 1L, 1);

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<int>("IdEndereco")
                        .HasColumnType("int");

                    b.HasKey("IdEnderecoEmpresa");

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("IdEndereco");

                    b.ToTable("EnderecoEmpresa");
                });

            modelBuilder.Entity("Entities.Entities.Endereco.EnderecoUnidade", b =>
                {
                    b.Property<int>("IdEnderecoUnidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_EnderecoUnidade");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEnderecoUnidade"), 1L, 1);

                    b.Property<int>("IdEndereco")
                        .HasColumnType("int");

                    b.Property<int>("IdUnidade")
                        .HasColumnType("int");

                    b.HasKey("IdEnderecoUnidade");

                    b.HasIndex("IdEndereco");

                    b.HasIndex("IdUnidade");

                    b.ToTable("EnderecoUnidade");
                });

            modelBuilder.Entity("Entities.Entities.Exames.AtendimentoExames", b =>
                {
                    b.Property<int>("IdAtendimentoExames")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_AtendimentoEmpresa");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAtendimentoExames"), 1L, 1);

                    b.Property<int?>("FuncionarioIdFuncionario")
                        .HasColumnType("int");

                    b.Property<int>("IdAtendimento")
                        .HasColumnType("int");

                    b.Property<int>("IdExame")
                        .HasColumnType("int");

                    b.HasKey("IdAtendimentoExames");

                    b.HasIndex("FuncionarioIdFuncionario");

                    b.HasIndex("IdAtendimento");

                    b.HasIndex("IdExame");

                    b.ToTable("AtendimentoExames");
                });

            modelBuilder.Entity("Entities.Entities.Exames.Exame", b =>
                {
                    b.Property<int>("IdExame")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_Exame");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdExame"), 1L, 1);

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("dataAlteracao_Exame");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2")
                        .HasColumnName("dataCadastro_Exame");

                    b.Property<int>("IdPrestador")
                        .HasColumnType("int");

                    b.Property<string>("NomeExame")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nome_Exame");

                    b.Property<bool>("SituacaoExame")
                        .HasColumnType("bit")
                        .HasColumnName("situacao_Exame");

                    b.HasKey("IdExame");

                    b.HasIndex("IdPrestador");

                    b.ToTable("Exame");
                });

            modelBuilder.Entity("Entities.Entities.Exames.FuncionarioExames", b =>
                {
                    b.Property<int>("IdFuncionarioExames")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_FuncionarioExames");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFuncionarioExames"), 1L, 1);

                    b.Property<int>("IdExame")
                        .HasColumnType("int");

                    b.Property<int>("IdFuncionario")
                        .HasColumnType("int");

                    b.HasKey("IdFuncionarioExames");

                    b.HasIndex("IdExame");

                    b.HasIndex("IdFuncionario");

                    b.ToTable("FuncionarioExames");
                });

            modelBuilder.Entity("Entities.Entities.Funcionarios.AtendimentoFuncionario", b =>
                {
                    b.Property<int>("IdAtendimentoFuncionario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_AtendimentoFuncionario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAtendimentoFuncionario"), 1L, 1);

                    b.Property<int>("IdAtendimento")
                        .HasColumnType("int");

                    b.Property<int>("IdFuncionario")
                        .HasColumnType("int");

                    b.HasKey("IdAtendimentoFuncionario");

                    b.HasIndex("IdAtendimento");

                    b.HasIndex("IdFuncionario");

                    b.ToTable("AtendimentoFuncionario");
                });

            modelBuilder.Entity("Entities.Entities.Funcionarios.Funcionario", b =>
                {
                    b.Property<int>("IdFuncionario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_Funcionario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFuncionario"), 1L, 1);

                    b.Property<string>("CpfFuncionario")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("cpf_Funcionario");

                    b.Property<DateTime>("DataAdmissao")
                        .HasColumnType("datetime2")
                        .HasColumnName("dataAdmissao_Funcionario");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("dataAlteracao_Funcionario");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2")
                        .HasColumnName("dataCadastro_Funcionario");

                    b.Property<DateTime?>("DataDemissao")
                        .HasColumnType("datetime2")
                        .HasColumnName("dataDemissao_Funcionario");

                    b.Property<DateTime>("DataNascimentoFuncionario")
                        .HasColumnType("datetime2")
                        .HasColumnName("dataNascimento_Funcionario");

                    b.Property<string>("EmailFuncionario")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("email_Funcionario");

                    b.Property<int>("IdCargo")
                        .HasColumnType("int");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<int>("IdSetor")
                        .HasColumnType("int");

                    b.Property<string>("NomeFuncionario")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nome_Funcionario");

                    b.Property<string>("PisFuncionario")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("pis_Funcionario");

                    b.Property<string>("RgFuncionario")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("rg_Funcionario");

                    b.Property<int>("SexoFuncionario")
                        .HasColumnType("int")
                        .HasColumnName("sexo_Funcionario");

                    b.Property<bool>("SituacaoFuncionario")
                        .HasColumnType("bit")
                        .HasColumnName("situacao_Funcionario");

                    b.Property<string>("TelefoneFuncionario")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("telefone_Funcionario");

                    b.HasKey("IdFuncionario");

                    b.HasIndex("IdCargo");

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("IdSetor");

                    b.ToTable("Funcionario");
                });

            modelBuilder.Entity("Entities.Entities.Pessoas.Pessoa", b =>
                {
                    b.Property<int>("IdPessoas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_Pessoas");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPessoas"), 1L, 1);

                    b.Property<string>("BairroPessoas")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("bairro_Pessoas");

                    b.Property<string>("CPFPessoas")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("cpf_Pessoas");

                    b.Property<string>("CepPessoas")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("cep_Pessoas");

                    b.Property<string>("CidadePessoas")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("cidade_Pessoas");

                    b.Property<string>("ComplementoPessoas")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("complemento_Pessoas");

                    b.Property<string>("ConselhoDeClasseEstadoPessoas")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("conselhoDeClasseEstado_Pessoas");

                    b.Property<string>("ConselhoDeClassePessoas")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("conselhoDeClasse_Pessoas");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("dataAlteracao_Pessoas");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2")
                        .HasColumnName("dataCadastro_Pessoas");

                    b.Property<string>("EmailPessoas")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("email_Pessoas");

                    b.Property<string>("EnderecoPessoas")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("endereco_Pessoas");

                    b.Property<int?>("EspecialidadePessoas")
                        .HasColumnType("int")
                        .HasColumnName("especialidade_Pessoas");

                    b.Property<string>("EstadoPessoas")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("estado_Pessoas");

                    b.Property<string>("NomePessoas")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nome_Pessoas");

                    b.Property<int>("NumeroPessoas")
                        .HasColumnType("int")
                        .HasColumnName("numero_Pessoas");

                    b.Property<string>("PISPessoas")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("pis_Pessoas");

                    b.Property<string>("RGPessoas")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("rg_Pessoas");

                    b.Property<string>("RQEPessoas")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("rqe_Pessoas");

                    b.Property<string>("SiglaConselhoDeClassePessoas")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("siglaConselhoDeClasse_Pessoas");

                    b.Property<bool>("StatusPessoas")
                        .HasColumnType("bit")
                        .HasColumnName("status_Pessoas");

                    b.Property<string>("TelelefoneCelularPessoas")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("telelefoneCelular_Pessoas");

                    b.Property<int?>("TipoPessoas")
                        .HasColumnType("int")
                        .HasColumnName("tipo_Pessoas");

                    b.HasKey("IdPessoas");

                    b.ToTable("Pessoa");
                });

            modelBuilder.Entity("Entities.Entities.Prestadores.Prestador", b =>
                {
                    b.Property<int>("IdPrestador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_Prestador");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPrestador"), 1L, 1);

                    b.Property<bool?>("AtendentePrestador")
                        .HasColumnType("bit")
                        .HasColumnName("atendente_Prestador");

                    b.Property<string>("CepPrestador")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("cep_Prestador");

                    b.Property<string>("CidadePrestador")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("cidade_Prestador");

                    b.Property<string>("ComplementoPrestador")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("complemento_Prestador");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("dataAlteracao_Prestador");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2")
                        .HasColumnName("dataCadastro_Prestador");

                    b.Property<string>("EnderecoPrestador")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("endereco_Prestador");

                    b.Property<string>("EstadoPrestador")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("estado_Prestador");

                    b.Property<string>("NomePrestador")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nome_Prestador");

                    b.Property<int?>("NumeroPrestador")
                        .HasColumnType("int")
                        .HasColumnName("numero_Prestador");

                    b.Property<string>("RazaoSocialPrestador")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("razaoSocial_Prestador");

                    b.Property<bool>("SitucaoPrestador")
                        .HasColumnType("bit")
                        .HasColumnName("situcao_Prestador");

                    b.Property<int?>("TipoPessoa")
                        .HasColumnType("int")
                        .HasColumnName("tipoPessoa_Prestador");

                    b.Property<int?>("TipoPrestador")
                        .HasColumnType("int")
                        .HasColumnName("tipoPrestador_Prestador");

                    b.Property<string>("cnpj_Prestador")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("cnpj_Prestador");

                    b.Property<string>("cpf_Prestador")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("cpf_Prestador");

                    b.Property<string>("email_Prestador")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("email_Prestador");

                    b.Property<string>("telefoneCelular_Prestador")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("telefoneCelular_Prestador");

                    b.Property<string>("telefone_Prestador")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("telefone_Prestador");

                    b.HasKey("IdPrestador");

                    b.ToTable("Prestador");
                });

            modelBuilder.Entity("Entities.Entities.Riscos.AtendimentoRiscos", b =>
                {
                    b.Property<int>("IdAtendimentoRiscos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_AtendimentoRiscos");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAtendimentoRiscos"), 1L, 1);

                    b.Property<int>("IdAtendimento")
                        .HasColumnType("int");

                    b.Property<int>("IdRisco")
                        .HasColumnType("int");

                    b.HasKey("IdAtendimentoRiscos");

                    b.HasIndex("IdAtendimento");

                    b.HasIndex("IdRisco");

                    b.ToTable("AtendimentoRiscos");
                });

            modelBuilder.Entity("Entities.Entities.Riscos.FuncionarioRisco", b =>
                {
                    b.Property<int>("IdFuncionarioExames")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_FuncionarioRisco");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFuncionarioExames"), 1L, 1);

                    b.Property<int>("IdFuncionario")
                        .HasColumnType("int");

                    b.Property<int>("IdRisco")
                        .HasColumnType("int");

                    b.HasKey("IdFuncionarioExames");

                    b.HasIndex("IdFuncionario");

                    b.HasIndex("IdRisco");

                    b.ToTable("FuncionarioRisco");
                });

            modelBuilder.Entity("Entities.Entities.Riscos.Risco", b =>
                {
                    b.Property<int>("IdRisco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_Risco");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRisco"), 1L, 1);

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("dataAlteracao_Risco");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2")
                        .HasColumnName("dataCadastro_Risco");

                    b.Property<int>("IdPrestador")
                        .HasColumnType("int");

                    b.Property<string>("NomeRisco")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nome_Risco");

                    b.Property<bool>("SituacaoRisco")
                        .HasColumnType("bit")
                        .HasColumnName("situacao_Risco");

                    b.Property<int>("TipoRisco")
                        .HasColumnType("int")
                        .HasColumnName("tipo_Risco");

                    b.HasKey("IdRisco");

                    b.HasIndex("IdPrestador");

                    b.ToTable("Risco");
                });

            modelBuilder.Entity("Entities.Entities.Setores.Setor", b =>
                {
                    b.Property<int>("IdSetor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_Setor");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSetor"), 1L, 1);

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("dataAlteracao_Setor");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2")
                        .HasColumnName("dataCadastro_Setor");

                    b.Property<string>("DescricaoSetor")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("descricao_Setor");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<string>("NomeSetor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nome_Setor");

                    b.Property<bool>("SituacaoSetor")
                        .HasColumnType("bit")
                        .HasColumnName("situacao_Setor");

                    b.HasKey("IdSetor");

                    b.HasIndex("IdEmpresa");

                    b.ToTable("Setor");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Entities.Entities.Atendimentos.Atendimento", b =>
                {
                    b.HasOne("Entities.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany("Atendimento")
                        .HasForeignKey("IdUsuarioAtendimento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Entities.Entities.Cargos.Cargo", b =>
                {
                    b.HasOne("Entities.Entities.Empresas.Empresa", "Empresa")
                        .WithMany("Cargo")
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Entities.Entities.Empresas.AtendimentoEmpresa", b =>
                {
                    b.HasOne("Entities.Entities.Atendimentos.Atendimento", "Atendimento")
                        .WithMany("AtendimentoEmpresa")
                        .HasForeignKey("IdAtendimento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Entities.Empresas.Empresa", "Empresa")
                        .WithMany("AtendimentoEmpresa")
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atendimento");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Entities.Entities.Empresas.PessoaEmpresa", b =>
                {
                    b.HasOne("Entities.Entities.ApplicationUser", null)
                        .WithMany("PessoaEmpresa")
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("Entities.Entities.Empresas.Empresa", "Empresa")
                        .WithMany("PessoaEmpresa")
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Entities.Pessoas.Pessoa", "Pessoa")
                        .WithMany("PessoaEmpresa")
                        .HasForeignKey("IdPessoas")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("Entities.Entities.Empresas.PrestadorEmpresa", b =>
                {
                    b.HasOne("Entities.Entities.Empresas.Empresa", "Empresa")
                        .WithMany("PrestadorEmpresa")
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Entities.Prestadores.Prestador", "Prestador")
                        .WithMany("PrestadorEmpresa")
                        .HasForeignKey("IdPrestador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("Prestador");
                });

            modelBuilder.Entity("Entities.Entities.Empresas.Unidade", b =>
                {
                    b.HasOne("Entities.Entities.Empresas.Empresa", "Empresa")
                        .WithMany("Unidade")
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Entities.Entities.Empresas.UsuarioEmpresa", b =>
                {
                    b.HasOne("Entities.Entities.Empresas.Empresa", "Empresa")
                        .WithMany("UsuarioEmpresa")
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Entities.Entities.Endereco.EnderecoEmpresa", b =>
                {
                    b.HasOne("Entities.Entities.Empresas.Empresa", "Empresa")
                        .WithMany("EnderecoEmpresa")
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Entities.Endereco.Endereco", "Endereco")
                        .WithMany("EnderecoEmpresa")
                        .HasForeignKey("IdEndereco")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("Entities.Entities.Endereco.EnderecoUnidade", b =>
                {
                    b.HasOne("Entities.Entities.Endereco.Endereco", "Endereco")
                        .WithMany("EnderecoUnidade")
                        .HasForeignKey("IdEndereco")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Entities.Empresas.Unidade", "Unidade")
                        .WithMany("EnderecoUnidade")
                        .HasForeignKey("IdUnidade")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Endereco");

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("Entities.Entities.Exames.AtendimentoExames", b =>
                {
                    b.HasOne("Entities.Entities.Funcionarios.Funcionario", null)
                        .WithMany("AtendimentoExames")
                        .HasForeignKey("FuncionarioIdFuncionario");

                    b.HasOne("Entities.Entities.Atendimentos.Atendimento", "Atendimento")
                        .WithMany("AtendimentoExames")
                        .HasForeignKey("IdAtendimento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Entities.Exames.Exame", "Exame")
                        .WithMany("AtendimentoExames")
                        .HasForeignKey("IdExame")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atendimento");

                    b.Navigation("Exame");
                });

            modelBuilder.Entity("Entities.Entities.Exames.Exame", b =>
                {
                    b.HasOne("Entities.Entities.Prestadores.Prestador", "Prestador")
                        .WithMany("Exame")
                        .HasForeignKey("IdPrestador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prestador");
                });

            modelBuilder.Entity("Entities.Entities.Exames.FuncionarioExames", b =>
                {
                    b.HasOne("Entities.Entities.Exames.Exame", "Exame")
                        .WithMany("FuncionarioExames")
                        .HasForeignKey("IdExame")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Entities.Funcionarios.Funcionario", "Funcionario")
                        .WithMany("FuncionarioExames")
                        .HasForeignKey("IdFuncionario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exame");

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("Entities.Entities.Funcionarios.AtendimentoFuncionario", b =>
                {
                    b.HasOne("Entities.Entities.Atendimentos.Atendimento", "Atendimento")
                        .WithMany("AtendimentoFuncionario")
                        .HasForeignKey("IdAtendimento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Entities.Funcionarios.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("IdFuncionario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atendimento");

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("Entities.Entities.Funcionarios.Funcionario", b =>
                {
                    b.HasOne("Entities.Entities.Cargos.Cargo", "Cargo")
                        .WithMany("Funcionario")
                        .HasForeignKey("IdCargo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Entities.Empresas.Empresa", "Empresa")
                        .WithMany("Funcionario")
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Entities.Setores.Setor", "Setor")
                        .WithMany("Funcionario")
                        .HasForeignKey("IdSetor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cargo");

                    b.Navigation("Empresa");

                    b.Navigation("Setor");
                });

            modelBuilder.Entity("Entities.Entities.Riscos.AtendimentoRiscos", b =>
                {
                    b.HasOne("Entities.Entities.Atendimentos.Atendimento", "Atendimento")
                        .WithMany("AtendimentoRiscos")
                        .HasForeignKey("IdAtendimento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Entities.Riscos.Risco", "Risco")
                        .WithMany("AtendimentoRiscos")
                        .HasForeignKey("IdRisco")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atendimento");

                    b.Navigation("Risco");
                });

            modelBuilder.Entity("Entities.Entities.Riscos.FuncionarioRisco", b =>
                {
                    b.HasOne("Entities.Entities.Funcionarios.Funcionario", "Funcionario")
                        .WithMany("FuncionarioRisco")
                        .HasForeignKey("IdFuncionario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Entities.Riscos.Risco", "Risco")
                        .WithMany("FuncionarioRisco")
                        .HasForeignKey("IdRisco")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcionario");

                    b.Navigation("Risco");
                });

            modelBuilder.Entity("Entities.Entities.Riscos.Risco", b =>
                {
                    b.HasOne("Entities.Entities.Prestadores.Prestador", "Prestador")
                        .WithMany("Risco")
                        .HasForeignKey("IdPrestador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prestador");
                });

            modelBuilder.Entity("Entities.Entities.Setores.Setor", b =>
                {
                    b.HasOne("Entities.Entities.Empresas.Empresa", "Empresa")
                        .WithMany("Setor")
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Entities.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Entities.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Entities.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Atendimento");

                    b.Navigation("PessoaEmpresa");
                });

            modelBuilder.Entity("Entities.Entities.Atendimentos.Atendimento", b =>
                {
                    b.Navigation("AtendimentoEmpresa");

                    b.Navigation("AtendimentoExames");

                    b.Navigation("AtendimentoFuncionario");

                    b.Navigation("AtendimentoRiscos");
                });

            modelBuilder.Entity("Entities.Entities.Cargos.Cargo", b =>
                {
                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("Entities.Entities.Empresas.Empresa", b =>
                {
                    b.Navigation("AtendimentoEmpresa");

                    b.Navigation("Cargo");

                    b.Navigation("EnderecoEmpresa");

                    b.Navigation("Funcionario");

                    b.Navigation("PessoaEmpresa");

                    b.Navigation("PrestadorEmpresa");

                    b.Navigation("Setor");

                    b.Navigation("Unidade");

                    b.Navigation("UsuarioEmpresa");
                });

            modelBuilder.Entity("Entities.Entities.Empresas.Unidade", b =>
                {
                    b.Navigation("EnderecoUnidade");
                });

            modelBuilder.Entity("Entities.Entities.Endereco.Endereco", b =>
                {
                    b.Navigation("EnderecoEmpresa");

                    b.Navigation("EnderecoUnidade");
                });

            modelBuilder.Entity("Entities.Entities.Exames.Exame", b =>
                {
                    b.Navigation("AtendimentoExames");

                    b.Navigation("FuncionarioExames");
                });

            modelBuilder.Entity("Entities.Entities.Funcionarios.Funcionario", b =>
                {
                    b.Navigation("AtendimentoExames");

                    b.Navigation("FuncionarioExames");

                    b.Navigation("FuncionarioRisco");
                });

            modelBuilder.Entity("Entities.Entities.Pessoas.Pessoa", b =>
                {
                    b.Navigation("PessoaEmpresa");
                });

            modelBuilder.Entity("Entities.Entities.Prestadores.Prestador", b =>
                {
                    b.Navigation("Exame");

                    b.Navigation("PrestadorEmpresa");

                    b.Navigation("Risco");
                });

            modelBuilder.Entity("Entities.Entities.Riscos.Risco", b =>
                {
                    b.Navigation("AtendimentoRiscos");

                    b.Navigation("FuncionarioRisco");
                });

            modelBuilder.Entity("Entities.Entities.Setores.Setor", b =>
                {
                    b.Navigation("Funcionario");
                });
#pragma warning restore 612, 618
        }
    }
}
